export const Types = {
    LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",

    REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",

    LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST",
    LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
    LOGOUT_USER_FAILED: "LOGOUT_USER_FAILED",

    GET_ALBUMS_REQUEST: "GET_ALBUMS_REQUEST",
    GET_ALBUMS_SUCCESS: "GET_ALBUMS_SUCCESS",
    GET_ALBUMS_FAILURE: "GET_ALBUMS_FAILURE",
    
    GET_ALBUM_REQUEST: "GET_ALBUM_REQUEST",
    GET_ALBUM_SUCCESS: "GET_ALBUM_SUCCESS",
    GET_ALBUM_FAILURE: "GET_ALBUM_FAILURE"
  }
