export const Types = {
    LOGIN_USER: "LOGIN_USER",
    REGISTER_USER: "REGISTER_USER",
    LOGOUT_USER: "LOGOUT_USER",
    LOGIN_FAILED: "LOGIN_FAILED",
    REGISTER_FAILED: "REGISTER_FAILED",
    GET_ALBUMS: "GET_ALBUMS"
  }
