# Generated by Django 3.2.8 on 2021-10-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_album_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
