# Generated by Django 3.2.8 on 2021-11-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_album_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
