# Generated by Django 3.2.8 on 2021-10-14 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['date_joined']},
        ),
    ]
