# Generated by Django 3.2.8 on 2021-10-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hide_email',
        ),
    ]
